#!/bin/sh

set -e

MESSAGE="$1"

if [ -z "$MESSAGE" ]; then
  echo "Usage: ./commit \"MESSAGE\""
  exit 1
fi

# Bump version in pom.xml (project version is the 2nd <version> tag)
CURRENT_VERSION=$(grep '<version>' pom.xml | sed -n '2p' | sed 's/.*<version>\([^<]*\)<\/version>/\1/')
MAJOR=$(echo "$CURRENT_VERSION" | cut -d. -f1)
MINOR=$(echo "$CURRENT_VERSION" | cut -d. -f2)
PATCH=$(echo "$CURRENT_VERSION" | cut -d. -f3 | cut -d- -f1)
PATCH=$((PATCH + 1))
NEW_VERSION="$MAJOR.$MINOR.$PATCH"
echo "Bumping version: $CURRENT_VERSION -> $NEW_VERSION"
sed -i.bak "s/<version>$CURRENT_VERSION<\/version>/<version>$NEW_VERSION<\/version>/" pom.xml && rm -f pom.xml.bak

git add -A
git status
git commit -m "$MESSAGE"
git push
